[package]
name = "net"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
thiserror = "1.0.31"
io-uring = { version = "0.5.2", features = ["unstable"] }
slab = "0.4.6"
libc = "0.2.126"
nix = "0.24.1"

binary = { path = "../binary" }
protocol = { path = "../protocol" }